apiVersion: apps/v1
kind: Deployment
metadata:
 name: details-deploy
 labels:
  app: details
spec:
 replicas: 2
 selector:
  matchLabels:
   app: details
 template:
  metadata:
   labels:
    app: details
  spec:
   containers:
   - name: detailsone-container
     image: nginx:stable-alpine
     ports:
     - containerPort: 80
   - name: detailsone-container
     image: alpine:latest
     
