apiVersion: v1
kind: Pod
metadata:
  name: eureka
  namespace: default
  labels:
    app: eureka
spec:
  containers:
  - name: eureka
    image: gcr.io/mavericsy-1732863904219/eureka:1.0
    ports:
    - containerPort: 8761
