apiVersion: v1
kind: Pod
metadata:
  name: productPage
  namespace: default
  labels:
    app: productPage
spec:
  containers:
  - name: latest
    image: alpine:latest
    command:
      - sleep
      - "5000"
  restartPolicy: Always
