server:
  port: 8088
spring:
  application:
    name: ratings
    cloud:
      config:
        enabled: false
        import-check:
          enabled: false

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/